#!/usr/bin/env python3
"""Sync the Agent Booster Pack doctrine into a personal ``~/AGENTS.md``.

The user's ``~/AGENTS.md`` is theirs to own; the pack's contribution lives
inside a single fenced block:

    <!-- ABP:BEGIN v<version> -->
    <!-- ... block boilerplate ... -->

    ## Agent Booster Pack

    ...canonical ``agents/AGENTS.md`` content...
    <!-- ABP:END -->

This script is the only sanctioned writer of that block. Anything outside
the markers is left untouched. Anything inside is replaced verbatim on
every run, so personal rules must live outside the markers.

Usage::

    python scripts/sync_agents_md.py             # apply if safe
    python scripts/sync_agents_md.py --check     # dry-run; do not write
    python scripts/sync_agents_md.py --force     # overwrite drift inside the block

Exit codes:
    0 — already in sync, or wrote successfully
    1 — would write (only in ``--check`` mode)
    2 — drift detected inside the block (use ``--force`` to overwrite)
    3 — target is a symlink (the stow install owns it; nothing to do)
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_AGENTS_MD = REPO_ROOT / "agents" / "AGENTS.md"
MARKETPLACE_JSON = REPO_ROOT / ".claude-plugin" / "marketplace.json"

BEGIN_RE = re.compile(r"^<!-- ABP:BEGIN(?: v([^ ]+))? -->\s*$", re.MULTILINE)
END_RE = re.compile(r"^<!-- ABP:END -->\s*$", re.MULTILINE)

BLOCK_BOILERPLATE = (
    "<!--\n"
    "Agent Booster Pack doctrine. Personal rules go OUTSIDE these markers.\n"
    "Content inside is regenerated by `scripts/sync_agents_md.py` on every\n"
    "run. Manual edits inside the block require `--force` to overwrite.\n"
    "-->\n"
)


class MarkerError(ValueError):
    """Raised when an existing ABP block has unsafe marker structure."""


def read_pack_version() -> str:
    data = json.loads(MARKETPLACE_JSON.read_text(encoding="utf-8"))
    return data["metadata"]["version"]


def strip_leading_h1(text: str) -> str:
    """Drop the canonical file's ``# AGENTS.md`` header so it doesn't
    collide with the user's own H1."""
    lines = text.splitlines()
    if not lines or not lines[0].lstrip().startswith("# "):
        return text
    cursor = 1
    while cursor < len(lines) and lines[cursor].strip() == "":
        cursor += 1
    body = "\n".join(lines[cursor:]).rstrip()
    return body + "\n" if body else ""


def build_block(version: str, body: str) -> str:
    return (
        f"<!-- ABP:BEGIN v{version} -->\n"
        f"{BLOCK_BOILERPLATE}"
        "\n"
        "## Agent Booster Pack\n"
        "\n"
        f"{body}"
        "<!-- ABP:END -->\n"
    )


def locate_block(text: str) -> tuple[int, int, str | None] | None:
    begins = list(BEGIN_RE.finditer(text))
    ends = list(END_RE.finditer(text))

    if not begins and not ends:
        return None

    if len(begins) != 1 or len(ends) != 1:
        raise MarkerError(
            "expected exactly one ABP:BEGIN marker and one ABP:END marker"
        )

    begin = begins[0]
    end = ends[0]
    if end.start() < begin.start():
        raise MarkerError("ABP:END appears before ABP:BEGIN")

    return begin.start(), end.end(), begin.group(1)


def block_inner(block_text: str) -> str:
    """Return the bytes between BEGIN and END markers (exclusive)."""
    begin = BEGIN_RE.search(block_text)
    end = END_RE.search(block_text)
    assert begin and end
    return block_text[begin.end() : end.start()]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync the Agent Booster Pack doctrine block into ~/AGENTS.md.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="dry-run: report what would change but do not write",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite the block even if it has been edited (drift)",
    )
    parser.add_argument(
        "--target",
        type=Path,
        default=Path.home() / "AGENTS.md",
        help="path to the AGENTS.md to update (default: ~/AGENTS.md)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    target: Path = args.target

    if target.is_symlink():
        print(
            f"{target} is a symlink — your stow install already owns this file.\n"
            "The sync script is only for users who keep a personal AGENTS.md.",
            file=sys.stderr,
        )
        return 3

    version = read_pack_version()
    canonical_body = strip_leading_h1(CANONICAL_AGENTS_MD.read_text(encoding="utf-8"))
    new_block = build_block(version, canonical_body)
    new_inner = block_inner(new_block)

    # Case 1: target does not exist — create with just the block.
    if not target.exists():
        if args.check:
            print(f"would create {target} with ABP block v{version}")
            return 1
        target.write_text(new_block, encoding="utf-8")
        print(f"created {target} with ABP block v{version}")
        return 0

    existing = target.read_text(encoding="utf-8")
    try:
        located = locate_block(existing)
    except MarkerError as error:
        print(
            f"malformed ABP block markers in {target}: {error}.\n"
            "The sync script will not write because it cannot prove which "
            "content is user-owned. Repair the markers manually, then re-run.",
            file=sys.stderr,
        )
        return 2

    # Case 2: no markers — append at the bottom.
    if located is None:
        if args.check:
            print(f"would append ABP block v{version} to {target}")
            return 1
        appended = existing.rstrip() + "\n\n" + new_block
        target.write_text(appended, encoding="utf-8")
        print(f"appended ABP block v{version} to {target}")
        return 0

    # Case 3: markers found — compare and update.
    start, end, current_version = located
    current_block = existing[start:end]
    current_inner = block_inner(current_block)

    if current_inner == new_inner and current_version == version:
        print(f"{target} ABP block already at v{version}")
        return 0

    if current_inner != new_inner and not args.force:
        diff = "\n".join(
            difflib.unified_diff(
                current_inner.splitlines(),
                new_inner.splitlines(),
                fromfile=f"{target.name} (v{current_version or '?'})",
                tofile=f"canonical (v{version})",
                lineterm="",
            )
        )
        print(
            f"drift detected inside the ABP block in {target}.\n"
            "Either the block was edited in place, or the canonical doctrine "
            "has moved.\n"
            "Move personal edits outside the markers, or re-run with --force "
            "to overwrite.",
            file=sys.stderr,
        )
        if diff:
            print(diff, file=sys.stderr)
        return 2

    if args.check:
        print(
            f"would update {target}: ABP block v{current_version or '?'} → v{version}"
        )
        return 1

    updated = existing[:start] + new_block + existing[end:]
    target.write_text(updated, encoding="utf-8")
    print(f"updated {target}: ABP block v{current_version or '?'} → v{version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
